Require nbconvert>=7.1.0
Fixes:
```
  File "/home/docs/checkouts/readthedocs.org/user_builds/parpe/envs/385/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 25, in <module>
    from lxml.html.clean import clean_html
  File "/home/docs/checkouts/readthedocs.org/user_builds/parpe/envs/385/lib/python3.11/site-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```