Fix RTD build (#386)
* Require nbconvert>=7.1.0

Fixes:
```
  File "/home/docs/checkouts/readthedocs.org/user_builds/parpe/envs/385/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 25, in <module>
    from lxml.html.clean import clean_html
  File "/home/docs/checkouts/readthedocs.org/user_builds/parpe/envs/385/lib/python3.11/site-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```

* m2r2 -> myst-parser

Fixes:
```
  File "/home/docs/checkouts/readthedocs.org/user_builds/parpe/envs/386/lib/python3.11/site-packages/m2r2.py", line 14, in <module>
    from docutils.core import ErrorString
ImportError: cannot import name 'ErrorString' from 'docutils.core' (/home/docs/checkouts/readthedocs.org/user_builds/parpe/envs/386/lib/python3.11/site-packages/docutils/core.py)
```